client_screener_task:
  description: >
    Analyze the data provided about the client and generate a score and analysis of the client's quality.
    The score should be between 0 and 5, where 5 is the highest quality and 0 is the lowest quality.
    The analysis should be a concise analysis of the client's score, including the client's location, rating, spend, and payment verified status.

    Your output should be concise and to the point. For example: "Strong rating due to US-based location, high spend, and high rating" or "Weak rating due to location and unverified payment"
    If you are not sure, return a client_score of 0 and a client_analysis of "Not sure: " + what you are not sure about.

    Client Score Criteria:
    - Client Score should start at 1 and increase by +1 for each of the following criteria:
    - If Payment Verified Status is True, increase the score by 1.
    - If Location is US, UK, Canada, Australia, or other developed countries, increase the score by 1.
    - If Rating is 0 but Total Spend is less than $1000, no change to the score.
    - If Total Spend is $1000 or more, increase the score by 1.
    - If Total Spend is $10000 or more, increase the score by 2.
    - If Rating is 4.5 or lower, decrease the score by 1.
    - If Rating is 4.0 or lower, decrease the score by 2.


    Client Information: {client_info}

  expected_output: >
    A JSON object following the following structure:
    - client_score: A score between 0 and 5, where 5 is the highest quality and 0 is the lowest quality
    - client_analysis: A very concise analysis (1-2 sentences) explaining the factors that contributed to the client's score.

red_flag_check_task:
  description: >
    Analyze the job description and determine if it violates any of the "red flag" criteria supplied by the candidate.
    If the job description violates any of the red flag criteria, provide a concise analysis of the red flag violation.
    By default, the job description does not violate any red flag criteria.
    You should only return a red_flag_violation of True if the job description explicitly violates any of the red flag criteria.
    If you are not sure, return a red_flag_violation of False and a red_flag_analysis of "Not sure if the job description violates any red flag criteria."

    Red Flag Criteria: {red_flag_criteria}

    Job Description: {job_info}
  expected_output: >
    A JSON object following the following structure:
    - red_flag_violation: True if the job description violates any of the red flag criteria, False otherwise
    - red_flag_analysis: A concise analysis (1-2 sentences) of the red flag violation, including the job's requirements, the candidates skills & experience, and any additional notes.
    - client_score: (provided by client_screener_task)
    - client_analysis: (provided by client_screener_task)
