red_flag_check_task:
  description: >
    Analyze the job description and determine if it violates any of the "red flag" criteria supplied by the candidate.
    If the job description violates any of the red flag criteria, provide a concise analysis of the red flag violation.
    By default, the job description does not violate any red flag criteria.
    You should only return a red_flag_violation of True if the job description explicitly violates any of the red flag criteria.
    If you are not sure, return a red_flag_violation of False and a red_flag_analysis of "Not sure if the job description violates any red flag criteria."

    Red Flag Criteria: {red_flag_criteria}

    Job Description: {job_info}
  expected_output: >
    A JSON object following the following structure:
    - red_flag_violation: True if the job description violates any of the red flag criteria, False otherwise
    - red_flag_analysis: A concise analysis of the red flag violation, including the job's requirements, the candidates skills & experience, and any additional notes.

read_cv_task:
  description: >
    Extract relevant information from the candidate's profile, including professional experience and freelance project history.
    Additionally, extract the candidate's technical skills and preferred coding languages and frameworks.
    Additionally, take into account the user's preferences in terms of what types of jobs they are interested in.

    Candidate Profile: {candidate_data}
  expected_output: >
    A structured summary of the Candidate Profile, including:
    - Professional Summary
    - Technical Skills
    - Work History
    - Job/Project Preferences

match_cv_task:
  description: >
    Match the Candidate to the job opportunity based on skills, experience, and project history.
    Evaluate how well the candidate's profile fits the job description,
    focusing on the alignment of skills, work history, and key achievements
    with the job requirements.
    Also take into account the candidate's preferences in terms of what types of jobs they are interested in.
    In your output, refer to the candidate by their name.

    Job information: {job_info}

    Candidate Profile: {candidate_data}
  expected_output: >
    A JSON object following the following structure:
    - job_title: The title of the job opportunity
    - match_strength: The strength of the match between the CV and the job on a scale of 0-5
    - match_analysis: A concise analysis of the match, including the job's requirements, the candidates skills & experience, and any additional notes. Refer to the candidate by their name.
