read_cv_task:
  description: >
    Extract relevant information from the candidate's profile, including professional experience and freelance project history.
    Additionally, extract the candidate's technical skills and preferred coding languages and frameworks.
    Additionally, take into account the user's preferences in terms of what types of jobs they are interested in.

    Candidate Profile: {candidate_data}
  expected_output: >
    A structured summary of the Candidate Profile, including:
    - Professional Summary
    - Technical Skills
    - Work History
    - Job/Project Preferences

match_cv_task:
  description: >
    Analyze the job description and the candidate's profile and match the candidate to the job opportunity based on skills, experience, and project history.
    Also take into account the candidate's preferences in terms of what types of jobs they are interested in.
    Based on your analysis, determine the strength of the match between the candidate and the job on a scale of 0-5, where 5 is the strongest match.

    Only include information that is directly relevant to the match analysis. 
    IMPORTANT:Do not include any information about the candidate that is not directly relevant to the job description.
    Do not state the candidate's name in your output, instead phrase your analysis as if you are talking directly to the candidate.
    Do not include any unnecessary information in your output, such as "Here is my analysis of the match between the candidate and the job:" or "Based on my analysis, the candidate's profile matches the job description."

    If you feel like you cannot confidently determine the strength of the match, return a match_strength of 0 and a match_analysis of "Need more information: " + your reasoning on why you cannot confidently determine the strength of the match.

    Examples of match_analysis:
    - "Strong match due to your extensive experience with WordPress plugin development and API integration."
    - "Weak match due to your lack of experience with React Native"
    - "Moderate match due to experience with FullStack developement, despite the job requesting UI/UXdesign experience"

    Job information: {job_info}

    Candidate Profile: {candidate_data}
  expected_output: >
    A JSON object following the following structure:
    - job_title: The title of the job opportunity
    - match_strength: The strength of the match between the CV and the job on a scale of 0-5, where 5 is the strongest match
    - match_analysis: A concise analysis (between 1-3 sentences) explaining how you determined the match strength.
