technical_intake_analysis_task:
  description: >
    Using your extensive technical expertise in {user_focus}, analyze the provided project request.
    Determine if the project request contains enough information so that an industry professional can provide a reasonable estimate of the project's technical complexity.

    Your output should be a boolean TRUE/FALSE value.
    Return FALSE if the project request is excessively short or vague, or does not contain a reasonable amount of detail.
    Otherwise, return TRUE.

    Analyze this project request from a technical perspective: {job_info}
  expected_output: >
    A JSON object following the following structure:
    - complete_description: A boolean TRUE/FALSE value.

technical_analysis_task:
  description: >
    Using your technical expertise, analyze the provided project request to extract and summarize key technical requirements and responsibilities.
            
    1. Identify the key technical requirements and skills
    2. Determine the primary tech stack and tools
    3. Analyze the technical responsibilities
    4. Note any specific technical experience requirements
    5. Identify any unique technical challenges or requirements

    Provide a concise but comprehensive technical summary that will be useful for 
    matching candidates and identifying potential red flags.

    Return your analysis in a clear, structured format.

    Analyze this project request from a technical perspective: {job_info}
  expected_output: >
    A JSON object following the following structure:
    - complete_description: (THIS WILL BE PROVIDED BY THE TECHNICAL INTAKE ANALYST)
    - technical_analysis: A structured summary of the Project Request, including: Key Technical Requirements, Primary Tech Stack, Technical Responsibilities
